"""012_add_org_stripe_connect

Revision ID: e02f9a0bff75
Revises: 3f0fdb304781
Create Date: 2026-05-24 18:00:04.151022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e02f9a0bff75'
down_revision: Union[str, Sequence[str], None] = '3f0fdb304781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('stripe_account_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('organizations', sa.Column('stripe_charges_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.create_unique_constraint(None, 'organizations', ['stripe_account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'stripe_charges_enabled')
    op.drop_column('organizations', 'stripe_account_id')
    # ### end Alembic commands ###
