"""023_add_user_plan_and_org_integrations

Revision ID: 4fcbd295e066
Revises: cf0a5d3e6b9c
Create Date: 2026-06-14 07:02:16.024192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4fcbd295e066'
down_revision: Union[str, Sequence[str], None] = 'cf0a5d3e6b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_integrations',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('webhook', name='integration_provider'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('encrypted_config', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_integrations_org_id'), 'org_integrations', ['org_id'], unique=False)

    # users.plan: ADD COLUMN can't auto-create the enum type the way CREATE TABLE
    # can - create it explicitly first, then reference it by name
    # (create_type=False), per migrations 008/018.
    plan_tier = postgresql.ENUM(
        'free', 'starter', 'pro', 'enterprise', name='plan_tier', create_type=False
    )
    plan_tier.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'users',
        sa.Column(
            'plan',
            sa.Enum('free', 'starter', 'pro', 'enterprise', name='plan_tier', create_type=False),
            server_default='free',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    sa.Enum(name='plan_tier').drop(op.get_bind(), checkfirst=False)
    op.drop_index(op.f('ix_org_integrations_org_id'), table_name='org_integrations')
    op.drop_table('org_integrations')
    # create_table auto-created this enum on upgrade; drop it explicitly so a
    # downgrade leaves no orphan type behind (per migrations 008/018).
    sa.Enum(name='integration_provider').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
