"""006_create_sections

Revision ID: 5d8a7c2316ee
Revises: 95cdea0e7af3
Create Date: 2026-05-24 08:44:30.116662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d8a7c2316ee'
down_revision: Union[str, Sequence[str], None] = '95cdea0e7af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'course_id', 'slug', name='uq_section_course_slug')
    )
    op.create_index('ix_section_course_position', 'sections', ['course_id', 'position'], unique=False)
    op.create_index(op.f('ix_sections_course_id'), 'sections', ['course_id'], unique=False)
    op.create_index(op.f('ix_sections_org_id'), 'sections', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sections_org_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_course_id'), table_name='sections')
    op.drop_index('ix_section_course_position', table_name='sections')
    op.drop_table('sections')
    # ### end Alembic commands ###
