"""003_create_user_org_membership

Revision ID: dd359c585403
Revises: 080f58cef1a1
Create Date: 2026-05-23 16:52:35.952738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd359c585403'
down_revision: Union[str, Sequence[str], None] = '080f58cef1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_org_memberships',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'instructor', 'student', name='membership_role'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'org_id', name='uq_membership_user_org')
    )
    op.create_index(op.f('ix_user_org_memberships_org_id'), 'user_org_memberships', ['org_id'], unique=False)
    op.create_index(op.f('ix_user_org_memberships_user_id'), 'user_org_memberships', ['user_id'], unique=False)
    op.create_index('uq_membership_owner_per_org', 'user_org_memberships', ['org_id'], unique=True, postgresql_where=sa.text("role = 'owner'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_membership_owner_per_org', table_name='user_org_memberships', postgresql_where=sa.text("role = 'owner'"))
    op.drop_index(op.f('ix_user_org_memberships_user_id'), table_name='user_org_memberships')
    op.drop_index(op.f('ix_user_org_memberships_org_id'), table_name='user_org_memberships')
    op.drop_table('user_org_memberships')
    # ### end Alembic commands ###
