"""005_add_org_custom_domain

Revision ID: 95cdea0e7af3
Revises: 60567a4860a1
Create Date: 2026-05-24 01:05:00.015742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95cdea0e7af3'
down_revision: Union[str, Sequence[str], None] = '60567a4860a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('custom_domain', sqlmodel.sql.sqltypes.AutoString(length=253), nullable=True))
    op.create_index(op.f('ix_organizations_custom_domain'), 'organizations', ['custom_domain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_custom_domain'), table_name='organizations')
    op.drop_column('organizations', 'custom_domain')
    # ### end Alembic commands ###
